### ISSUE TITLE
MANIFEST is deprecated

### ISSUE THREAD

**Issue by quozl** [163gal/ShowJPEG#2]

**Comment by yell0wfl4sh** [comment]
@quozl I am seeing this issue being opened in many repositories, can you please explain this in detail to me. I am considering solving these issues.

**Comment by quozl** [comment]
Sure, happy to explain.

Originally the MANIFEST file contained a list of files that should be in an activity bundle.  You can find evidence of this at wiki.laptop.org if you are really interested in the history.

Eight years ago it was decided that MANIFEST was confusing activity authors, and complicating our bundle installation logic.  You can see that in [Sugar Toolkit commit e7430fa](https://github.com/sugarlabs/sugar-toolkit/commit/e7430faac9735eca60e33a5fb34f2a5a7cbe238e).

So a MANIFEST file may be deleted, and any use of the MANIFEST file by the activity itself should be re-engineered to use some other method.  It is not a simple file removal, but a review of the source code to make sure it can be removed and still have the activity build and run.

When I find a MANIFEST file, I log the issue.  Usually I find it on activities that;
* are more than eight years old, and/or;
* do not work at all!

Since fixing this issue requires building and running an activity on the current release of Sugar, it is not a simple task if the activity does not work.  So check the other issues, and see if you are willing to contribute a fix.

Just removing the file without evidence that you've done the build and run steps will make me ask interesting questions.  :grin:

**Comment by yell0wfl4sh** [comment]
@quozl Do you know how this issue was fixed in other active activities?
Maybe I'll get some lead because I am quite lost here on how to even start.

**Comment by quozl** [comment]
Pretty much as I said above; was there something that I needed to explain in more detail?  Please be specific.  Here's what I said;

> a MANIFEST file may be deleted, and any use of the MANIFEST file by the activity itself should be re-engineered to use some other method. It is not a simple file removal, but a review of the source code to make sure it can be removed and still have the activity build and run.

Breaking this task down into component tasks;
- [x] review all the source code of the activity; pretty quick as there are only three files,
- [x] search for any references to MANIFEST (in any activity I've not reviewed, there's maybe a 5% chance there will be a reference; it is a rare thing),
- [x] work to remove the references by re-engineering the code that makes reference,
- [x] remove the MANIFEST file,
- [x] try building the activity, (`python setup.py build`),
- [x] try running the activity, (`sugar-activity .`),
- [x] if all is good, commit the change and push.

**Comment by yell0wfl4sh** [comment]
This issue can now be closed. Thanks for guiding!
